[extend]
useDefault = true

[[rules]]
id = "institutional-ip"
description = "Real cluster IP address"
regex = '''132\.72\.105\.\d+'''
tags = ["ip", "network"]

[[rules]]
id = "institutional-hostname"
description = "Real institutional hostname"
regex = '''(example\.com|auth\.example|hpc-cluster\.example)'''
tags = ["hostname", "network"]

[[rules]]
id = "real-ad-server"
description = "Real AD/LDAP server"
regex = '''auth\.example'''
tags = ["ldap", "ad"]

[[rules]]

[[rules]]
id = "real-email"
description = "Real institutional email"
regex = '''[\w\.\-]+@(example\.com)'''
tags = ["email"]

[allowlist]
description = "Global allowlist"
paths = [
  '''.gitleaks.toml''',
  '''docs/setup.md''',
]
